#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom assertthat assert_that
#' @importFrom glue glue
#' @importFrom graphics abline
#' @importFrom graphics barplot
#' @importFrom graphics lines
#' @importFrom graphics par
#' @importFrom graphics title
#' @importFrom grDevices cairo_pdf
#' @importFrom grDevices dev.cur
#' @importFrom grDevices dev.list
#' @importFrom grDevices dev.off
#' @importFrom grDevices dev.set
#' @importFrom grDevices png
#' @importFrom lubridate hour
#' @importFrom lubridate minute
#' @importFrom lubridate second
#' @importFrom methods as
#' @importFrom methods is
#' @importFrom methods new
#' @importFrom rlang as_quosures
#' @importFrom rlang enquos
#' @importFrom rlang eval_tidy
#' @importFrom rlang is_named
#' @importFrom rlang is_scalar_double
#' @importFrom rlang is_scalar_integer
#' @importFrom rlang quo
#' @importFrom rlang quo_get_expr
#' @importFrom stats approx
#' @importFrom stats approxfun
#' @importFrom stats as.dist
#' @importFrom stats as.formula
#' @importFrom stats cmdscale
#' @importFrom stats end
#' @importFrom stats lowess
#' @importFrom stats model.matrix
#' @importFrom stats na.omit
#' @importFrom stats start
#' @importFrom stringr str_c
#' @importFrom stringr str_match
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom utils read.csv
#' @importFrom utils read.table
#' @importFrom utils write.table
## usethis namespace: end
NULL
